/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/island/model.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/model.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat22} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat10} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.mat9} />
      <mesh geometry={nodes['Node-Mesh_3'].geometry} material={materials.mat18} />
      <mesh geometry={nodes['Node-Mesh_4'].geometry} material={materials.mat21} />
      <mesh geometry={nodes['Node-Mesh_5'].geometry} material={materials.mat6} />
      <mesh geometry={nodes['Node-Mesh_6'].geometry} material={materials.mat4} />
      <mesh geometry={nodes['Node-Mesh_7'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_8'].geometry} material={materials.mat13} />
      <mesh geometry={nodes['Node-Mesh_9'].geometry} material={materials.mat12} />
      <mesh geometry={nodes['Node-Mesh_10'].geometry} material={materials.mat0} />
      <mesh geometry={nodes['Node-Mesh_11'].geometry} material={materials.mat15} />
    </group>
  )
}

useGLTF.preload('/model.glb')
